parameters:
    env(SENTRY_DSN): ''
    env(SENTRY_ENVIRONMENT): '%kernel.environment%'

sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%env(SENTRY_ENVIRONMENT)%'
    register_error_listener: false
