monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: notice
            handler: stderr
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        stderr:
            type: stream
            path: "php://stderr"
            level: debug
        sentry:
            type: service
            id: Sentry\Monolog\Handler
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
