name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check security vulnerabilities
        uses: symfonycorp/security-checker-action@v2

      - name: Run tests
        run: XDEBUG_MODE=coverage bin/phpunit --coverage-clover coverage.xml

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV }}
